### ISSUE TITLE
Make port and hostname dynamic via CLI 

### ISSUE THREAD

**Issue by andela-joyebanji** [dhtml/phpsocket.io#1]
I see you're limiting the port to "2000" => https://github.com/dhtml/phpsocket.io/blob/master/server/server.php#L9 and Host to "0.0.0.0" https://github.com/dhtml/phpsocket.io/blob/master/server/server.php#L12.

Why not make them injectable in CLI .... like 

```
   php server.php -p 8000 -h 127.0.0.1
```

and when none is passed to default to 2000 and 0.0.0.0

**Comment by dhtml** [comment]
That is a good idea, but the port can be configured to any value in the configuration.
